config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

urlpatterns += [
    path("", include("django_starter_buttercms.content.urls", namespace="content")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_starter_buttercms/content/urls.py
from django.urls import path

from .views import (
    ButterCMSBlogPostView,
    ButterCMSBlogSearchView,
    ButterCMSBlogView,
    ButterCMSPageView,
)

app_name = "content"
urlpatterns = [
    # HomePage Routes

    # The default home page is under "landing-page-with-components" slug, so let's add a root path to reflect that
    path("", ButterCMSPageView.as_view(), {"slug": "landing-page-with-components"}, name="home",),

    # Let's also add a backup landing-page route. This allows the user to create and test multiple 
    # landing pages and allows for configuration of both '/' and '/landing-page/' in Butter
    # iframe preview panel.
    path (
        "landing-page/<str:slug>/",
        ButterCMSPageView.as_view(),
        name="landing-pages",
    ),

    #Blog List View
    path("blog/", ButterCMSBlogView.as_view(), {"locale_slug": "en"}, name="blog"),

    # Blog Search View
    path("blog/search/", ButterCMSBlogSearchView.as_view(), {"locale_slug": "en"}, name="blog_search"),
    
    #Blog Detail View
    path("blog/<str:slug>/", ButterCMSBlogPostView.as_view(), {"locale_slug": "en"}, name="blog_post"),

    # Blog Categories View
    path(
        "blog/category/<str:category_slug>/",
        ButterCMSBlogView.as_view(),
        {"locale_slug": "en"},
        name="blog_category",
    ),
    # Blog Tag View
    path(
        "blog/tag/<str:tag_slug>/", ButterCMSBlogView.as_view(), {"locale_slug": "en"}, name="blog_tags"
    ),

    # Note: Deleted catchall route due to conflict with locale_home view

    # Localized Views:

    # Localized Home View:
    path("<str:locale_slug>/", ButterCMSPageView.as_view(), {"slug":"landing-page-with-components"},
        name="home",
    ),

    # Landing Page Backup Route
    path (
        "<str:locale_slug>/landing-page/<str:slug>/",
        ButterCMSPageView.as_view(),
        name="landing-pages",
    ),

    # Blog List Paths
    path("<str:locale_slug>/blog/", ButterCMSBlogView.as_view(), name="blog"),

    # Blog Search View
    path("<str:locale_slug>/blog/search/", ButterCMSBlogSearchView.as_view(), name="blog_search"),
    
    #Blog Detail View
    path("<str:locale_slug>/blog/<str:slug>/", view=ButterCMSBlogPostView.as_view(), name="blog_post"),

    # Blog Categories View
    path(
        "<str:locale_slug>/blog/category/<str:category_slug>/",
        view=ButterCMSBlogView.as_view(),
        name="blog_category",
    ),
    # Blog Tag View
    path(
        "<str:locale_slug>/blog/tag/<str:tag_slug>/", view=ButterCMSBlogView.as_view(), name="blog_tags"
    ),
    # And a path for all the other slugs, that can be accessed directly
    path("<str:locale_slug>/<str:slug>/", view=ButterCMSPageView.as_view(), name="buttercms_view"),
]

django_starter_buttercms/content/views.py
from django.conf import settings
from django.http import Http404
from django.utils import dateparse
from django.template.exceptions import TemplateDoesNotExist
from django.template.loader import get_template
from django.views.generic import TemplateView
from django.views.decorators.clickjacking import xframe_options_exempt
from requests.exceptions import HTTPError

from common.buttercms import client
import logging
logger = logging.getLogger(__name__)

class ButterCMSPageView(TemplateView):
    template_name = "content/page.html"

    @xframe_options_exempt
    def get(self, request, slug, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            page = self.get_page("landing-page", slug, preview=preview)
            
            # Prepare template names for components
            for component in page.get("fields", {}).get("body", []):
                # Check that the this project has a template for this component
                template_name = f"content/component/{component.get('type')}.html"
                try:
                    get_template(template_name)
                except TemplateDoesNotExist:
                    # Template doesn't seem to exist, so let's set it to fallback
                    template_name = "content/partials/missing-component.html"

                component["template_name"] = template_name
        

            context["page"] = page
            context["blog_posts"] = self.get_blog_posts()
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)

    def get_page(self, page_type, slug, preview=None):
        """
        Return page from ButterCMS. Raise 404 if the page is not found
        """
        params = {"preview": 1} if preview else None
        
        try:
            butter_page = client.pages.get(
                page_type, slug, params=params
            )  # Use "*" to search through all Page Types
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

        return butter_page.get("data")


    def get_blog_posts(self, category_slug=None, tag_slug=None, preview=None):
        """
        Return a list of blog posts from ButterCMS. Raise 404 if the page is not found
        """
        kwargs = {"page_size": 3, "page": 1, "exclude_body": "true"}
        if category_slug:
            kwargs.update({"category_slug": category_slug})
        if tag_slug:
            kwargs.update({"tag_slug": tag_slug})
        if preview:
            kwargs.update({"preview": preview})
        try:
            blog_posts = client.posts.all(params=kwargs)
            blog_posts_data = blog_posts.get("data", [])
            for post in blog_posts_data:
                post['published'] = dateparse.parse_datetime(post['published'])
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

        return blog_posts_data

    def search_blog_posts(self, query, preview=None):
        """
        Return a list of blog posts from ButterCMS that match the search query.

        Raise 404 if the page is not found.
        """
        kwargs = {"page_size": 3, "page": 1, "exclude_body": "true"}
        if preview:
            kwargs.update({"preview": preview})
        try:
            blog_posts = client.posts.search(query=query, params=kwargs)
            blog_posts_data = blog_posts.get("data", [])
            for post in blog_posts_data:
                post['published'] = dateparse.parse_datetime(post['published'])
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404
        return blog_posts_data

    def get_navigation_menu(self):
        """
        Return a navigation menu from ButterCMS. Raise 404 if the "Main menu" is not found
        """
        butter_navigation_menu = client.content_fields.get(["navigation_menu"])
        navigation_menus = butter_navigation_menu.get("data", {}).get(
            "navigation_menu", []
        )

        main_menu = [
            menu for menu in navigation_menus if menu.get("name") == "Main menu"
        ]

        if not main_menu:
            raise Http404

        return main_menu[0]


class ButterCMSBlogView(ButterCMSPageView):
    template_name = "content/blog.html"

    @xframe_options_exempt
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            category_slug = kwargs.get("category_slug")
            tag_slug = kwargs.get("tag_slug")
            context["blog_posts"] = self.get_blog_posts(
                category_slug=category_slug, tag_slug=tag_slug, preview=preview
            )
            context["category_slug"] = category_slug
            context["tag_slug"] = tag_slug
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)


class ButterCMSBlogSearchView(ButterCMSPageView):
    template_name = "content/blog.html"

    @xframe_options_exempt
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            search_query = request.GET.get("q")
            preview = request.GET.get("preview")
            context["blog_posts"] = self.search_blog_posts(search_query)
            context["search_query"] = search_query
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)


class ButterCMSBlogPostView(ButterCMSBlogView):
    template_name = "content/blog-post.html"

    @xframe_options_exempt
    def get(self, request, slug, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            blog_post = self.get_blog_post(slug)
            context["blog_post"] = blog_post
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)

    def get_blog_post(self, slug):
        """
        Return a blog post from ButterCMS. Raise 404 if the post is not found
        """
        try:
            butter_post = client.posts.get(slug)
            post_data = butter_post.get("data")
            post_data['published'] = dateparse.parse_datetime(post_data['published'])

            return post_data
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

django_starter_buttercms/templates/content/blog-post.html
{% extends 'content/base.html' %}
{% load static %}

{% block title %}{{ blog_post.seo_title }}{% endblock %}
{% if blog_post.meta_description %}
    {% block description %}{{ blog_post.meta_description }}{% endblock %}
{% endif %}
{% if blog_post.featured_image %}
    {% block seo_featured_image %}{{ blog_post.featured_image }}{% endblock seo_featured_image %}
{% endif %}

{% block css_extra %}
{% endblock css_extra %}

{% block navigation_menu %}

<div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
    <div class="ms-auto">
        <ul id="nav" class="navbar-nav ms-auto">
            {% for menu_item in navigation_menu.menu_items %}
            <li class="nav-item">
                <a class="{% if menu_item.label == 'Blog' %}active{% endif %}" href="/{{ menu_item.url }}">{{ menu_item.label }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

{% block main %}
    {% if not no_token %}
    {% if blog_post %}
        <!-- ========================= blog-section start ========================= -->

        <section id="blog-header" class="single-post-nav">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <h2>{{ blog_post.title }}</h2>
                            <ul class="breadcrumb-nav">
                                <li><a href="{% url 'content:home' %}">Home</a></li>
                                <li><a href="{% url 'content:blog' %}">Blog</a></li>
                                <li>{{ blog_post.title }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Post -->
        <section class="blog-post">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-12 col-12">
                        <div class="single-post">
                            <div class="single-post-meta">
                                <h2 class="single-post-header">{{ blog_post.title }}</h2>
                                <ul class="single-post-meta-info">
                                    <li>
                                        <a href="javascript:void(0)"><img src="{% if blog_post.author.profile_image %}{{ blog_post.author.profile_image }}{% else %}{% static 'images/team/team-1.png' %}{% endif %}" alt="#">{{ blog_post.author.first_name }} {{ blog_post.author.last_name }}</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0)"><i class="lni lni-calendar"></i> {{ blog_post.published }}
                                    </a>
                                    </li>
                                    {% for tag in blog_post.tags %}
                                    <li>
                                        <a href="{% url 'content:blog_tags' locale_slug=locale tag_slug=tag.slug %}"><i class="lni lni-tag"></i>{{ tag.name }}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% if blog_post.featured_image %}
                            <div class="single-post-thumbnail">
                                <img src="{{ blog_post.featured_image }}" alt="{{ blog_post.featured_image_alt }}">
                            </div>
                            {% endif %}
                            <div class="single-post-body">
                                {{ blog_post.body|safe }}
                            </div>
                        </div>
                    </div>
                    <!-- Searchbox -->
                    {% include "content/partials/blog-search-and-categories.html" %}
                </div>
            </div>
        </section>
        <!-- ========================= blog-section end ========================= -->
    {% endif %}
    {% endif %}
    <!-- ========================= Body components end ========================= -->
{% endblock %}

{% block js_extra %}
{% endblock js_extra %}

django_starter_buttercms/templates/content/blog.html
{% extends 'content/base.html' %}
{% load static %}

{% block title %}Sample Blog with Components - powered by ButterCMS{% endblock %}
{% block description %}Sample Landing Page with Components - powered by ButterCMS{% endblock %}

{% block css_extra %}
{% endblock css_extra %}

{% block navigation_menu %}

<div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
    <div class="ms-auto">
        <ul id="nav" class="navbar-nav ms-auto">
            {% for menu_item in navigation_menu.menu_items %}
            <li class="nav-item">
                <a class="{% if menu_item.label == 'Blog' %}active{% endif %}" href="/{{ menu_item.url }}">{{ menu_item.label }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

{% block main %}
        <!-- ========================= blog-roll section start ========================= -->
    {% if not no_token %}
    <section id="blog-roll" class="blog-roll-nav">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">

                    {% if category_slug %}
                    <!-- Breadcrumb nav for categories view -->
                    <div class="section-title text-center">
                        <h2>Blog Posts by Category</h2>
                        <ul class="breadcrumb-nav">
                            <li><a href="{% url 'content:home' locale_slug=locale %}">Home</a></li>
                            <li><a href="{% url 'content:blog' locale_slug=locale %}">Blog</a></li>
                            <li>Category: {{ category_slug }}</li>
                        </ul>
                    </div>
                    <!-- End Nav -->
                    {% elif tag_slug %}
                    <!-- Breadcrumb nav for posts by tag view -->
                    <div class="section-title text-center">
                        <h2>Blog Posts by Tag</h2>
                        <ul class="breadcrumb-nav">
                            <li><a href="{% url 'content:home' locale_slug=locale %}">Home</a></li>
                            <li><a href="{% url 'content:blog' locale_slug=locale %}">Blog</a></li>
                            <li>Tag: {{ tag_slug }}</li>
                        </ul>
                    </div>
                    <!-- End Nav -->
                    {% elif search_query %}
                    <!-- Breadcrumb nav for search view -->
                    <div class="section-title text-center">
                        <h2>Search Results</h2>
                        <ul class="breadcrumb-nav">
                            <li><a href="{% url 'content:home' locale_slug=locale %}">Home</a></li>
                            <li><a href="{% url 'content:blog' locale_slug=locale %}">Blog</a></li>
                            <li>Seach: "{{search_query}}"</li>
                        </ul>
                    </div>
                    <!-- End Nav -->
                    {% else %}
                    <!-- Breadcrumb nav for main blog.html view -->
                    <div class="section-title text-center">
                        <h2>All Blog Posts</h2>
                        <ul class="breadcrumb-nav">
                            <li><a href="{% url 'content:home' locale_slug=locale %}">Home</a></li>
                            <li>All blog posts</li>
                        </ul>
                    </div>
                    <!-- End Nav -->
                    {% endif %}

                </div>
            </div>
        </div>
    </section>
    <!-- Blog Post -->
    <section class="blog-posts">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-8 blog-roll-cards">
                    <div class="row"><!--nested row for blogroll-->
                        {% for blog_post in blog_posts %}
                        <div class="col-12 col-lg-6">
                            <div class="blog-roll-card">
                                <div class="blog-roll-card-meta">
                                    <h2 class="blog-roll-card-header"><a href="{% url 'content:blog_post' slug=blog_post.slug %}">{{ blog_post.title }}</a></h2>
                                    <ul class="blog-roll-card-meta-info">
                                        <li>
                                            <a href="javascript:void(0)"><img src="{% if blog_post.author.profile_image %}{{ blog_post.author.profile_image }}{% else %}{% static 'images/team/team-1.png' %}{% endif %}" alt="#">{{ blog_post.author.first_name }} {{ blog_post.author.last_name }}</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)"><i class="lni lni-calendar"></i> {{ blog_post.published }}
                                        </a>
                                        </li>
                                        {% for tag in blog_post.tags %}
                                        <li>
                                            <a href="{% url 'content:blog_tags' locale_slug=locale tag_slug=tag.slug %}"><i class="lni lni-tag"></i> {{ tag.name }}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                {% if blog_post.featured_image %}
                                <div class="single-post-thumbnail">
                                    <img src="{{ blog_post.featured_image }}" alt="">
                                </div>
                                {% endif %}
                                <div class="blog-roll-card-body">
                                    <p>{{ blog_post.summary }}</p>
                                </div>
                                <div class="blog-roll-card-footer text-center">
                                    <a href="{% url 'content:blog_post' locale_slug=locale slug=blog_post.slug %}" class="main-btn btn-hover">Read More</a>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                          <div>No blog posts found.</div>
                        {% endfor %}
                    </div>
                </div>
                <!-- Widgets Column -->
               {% include "content/partials/blog-search-and-categories.html" %}
            </div>
        </div>
    </section>
    <!-- ========================= blog-section end ========================= -->
    {% endif %}
{% endblock %}

{% block js_extra %}
{% endblock js_extra %}

django_starter_buttercms/templates/content/page.html
{% extends 'content/base.html' %}

{% block title %}{{ page.fields.seo.title }}{% endblock %}
{% block description %}{{ page.fields.seo.description }}{% endblock %}

{% block main %}
    <!-- ========================= Body components ========================= -->
    {% if page %}
        {% for component in page.fields.body %}
            {% include component.template_name with component=component.fields component_name=component.type %}
        {% endfor %}
    {% endif %}

    {% if blog_posts %}
        {% include "content/partials/blog-posts.html" %}
    {% endif %}
    <!-- ========================= Body components end ========================= -->
{% endblock %}