config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

urlpatterns += [
    path("", include("django_starter_buttercms.content.urls", namespace="content")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_starter_buttercms/content/urls.py
from django.urls import path

from .views import (
    ButterCMSBlogPostView,
    ButterCMSBlogSearchView,
    ButterCMSBlogView,
    ButterCMSPageView,
)

app_name = "content"
urlpatterns = [
    # HomePage Routes

    # The default home page is under "landing-page-with-components" slug, so let's add a root path to reflect that
    path("", ButterCMSPageView.as_view(), {"slug": "landing-page-with-components"}, name="home",),

    # Let's also add a backup landing-page route. This allows the user to create and test multiple 
    # landing pages and allows for configuration of both '/' and '/landing-page/' in Butter
    # iframe preview panel.
    path (
        "landing-page/<str:slug>/",
        ButterCMSPageView.as_view(),
        name="landing-pages",
    ),

    #Blog List View
    path("blog/", ButterCMSBlogView.as_view(), {"locale_slug": "en"}, name="blog"),

    # Blog Search View
    path("blog/search/", ButterCMSBlogSearchView.as_view(), {"locale_slug": "en"}, name="blog_search"),
    
    #Blog Detail View
    path("blog/<str:slug>/", ButterCMSBlogPostView.as_view(), {"locale_slug": "en"}, name="blog_post"),

    # Blog Categories View
    path(
        "blog/category/<str:category_slug>/",
        ButterCMSBlogView.as_view(),
        {"locale_slug": "en"},
        name="blog_category",
    ),
    # Blog Tag View
    path(
        "blog/tag/<str:tag_slug>/", ButterCMSBlogView.as_view(), {"locale_slug": "en"}, name="blog_tags"
    ),

    # Note: Deleted catchall route due to conflict with locale_home view

    # Localized Views:

    # Localized Home View:
    path("<str:locale_slug>/", ButterCMSPageView.as_view(), {"slug":"landing-page-with-components"},
        name="home",
    ),

    # Landing Page Backup Route
    path (
        "<str:locale_slug>/landing-page/<str:slug>/",
        ButterCMSPageView.as_view(),
        name="landing-pages",
    ),

    # Blog List Paths
    path("<str:locale_slug>/blog/", ButterCMSBlogView.as_view(), name="blog"),

    # Blog Search View
    path("<str:locale_slug>/blog/search/", ButterCMSBlogSearchView.as_view(), name="blog_search"),
    
    #Blog Detail View
    path("<str:locale_slug>/blog/<str:slug>/", view=ButterCMSBlogPostView.as_view(), name="blog_post"),

    # Blog Categories View
    path(
        "<str:locale_slug>/blog/category/<str:category_slug>/",
        view=ButterCMSBlogView.as_view(),
        name="blog_category",
    ),
    # Blog Tag View
    path(
        "<str:locale_slug>/blog/tag/<str:tag_slug>/", view=ButterCMSBlogView.as_view(), name="blog_tags"
    ),
    # And a path for all the other slugs, that can be accessed directly
    path("<str:locale_slug>/<str:slug>/", view=ButterCMSPageView.as_view(), name="buttercms_view"),
]

django_starter_buttercms/content/views.py
from django.conf import settings
from django.http import Http404
from django.utils import dateparse
from django.template.exceptions import TemplateDoesNotExist
from django.template.loader import get_template
from django.views.generic import TemplateView
from django.views.decorators.clickjacking import xframe_options_exempt
from requests.exceptions import HTTPError

from common.buttercms import client
import logging
logger = logging.getLogger(__name__)

class ButterCMSPageView(TemplateView):
    template_name = "content/page.html"

    @xframe_options_exempt
    def get(self, request, slug, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            page = self.get_page("landing-page", slug, preview=preview)
            
            # Prepare template names for components
            for component in page.get("fields", {}).get("body", []):
                # Check that the this project has a template for this component
                template_name = f"content/component/{component.get('type')}.html"
                try:
                    get_template(template_name)
                except TemplateDoesNotExist:
                    # Template doesn't seem to exist, so let's set it to fallback
                    template_name = "content/partials/missing-component.html"

                component["template_name"] = template_name
        

            context["page"] = page
            context["blog_posts"] = self.get_blog_posts()
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)

    def get_page(self, page_type, slug, preview=None):
        """
        Return page from ButterCMS. Raise 404 if the page is not found
        """
        params = {"preview": 1} if preview else None
        
        try:
            butter_page = client.pages.get(
                page_type, slug, params=params
            )  # Use "*" to search through all Page Types
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

        return butter_page.get("data")


    def get_blog_posts(self, category_slug=None, tag_slug=None, preview=None):
        """
        Return a list of blog posts from ButterCMS. Raise 404 if the page is not found
        """
        kwargs = {"page_size": 3, "page": 1, "exclude_body": "true"}
        if category_slug:
            kwargs.update({"category_slug": category_slug})
        if tag_slug:
            kwargs.update({"tag_slug": tag_slug})
        if preview:
            kwargs.update({"preview": preview})
        try:
            blog_posts = client.posts.all(params=kwargs)
            blog_posts_data = blog_posts.get("data", [])
            for post in blog_posts_data:
                post['published'] = dateparse.parse_datetime(post['published'])
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

        return blog_posts_data

    def search_blog_posts(self, query, preview=None):
        """
        Return a list of blog posts from ButterCMS that match the search query.

        Raise 404 if the page is not found.
        """
        kwargs = {"page_size": 3, "page": 1, "exclude_body": "true"}
        if preview:
            kwargs.update({"preview": preview})
        try:
            blog_posts = client.posts.search(query=query, params=kwargs)
            blog_posts_data = blog_posts.get("data", [])
            for post in blog_posts_data:
                post['published'] = dateparse.parse_datetime(post['published'])
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404
        return blog_posts_data

    def get_navigation_menu(self):
        """
        Return a navigation menu from ButterCMS. Raise 404 if the "Main menu" is not found
        """
        butter_navigation_menu = client.content_fields.get(["navigation_menu"])
        navigation_menus = butter_navigation_menu.get("data", {}).get(
            "navigation_menu", []
        )

        main_menu = [
            menu for menu in navigation_menus if menu.get("name") == "Main menu"
        ]

        if not main_menu:
            raise Http404

        return main_menu[0]


class ButterCMSBlogView(ButterCMSPageView):
    template_name = "content/blog.html"

    @xframe_options_exempt
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            category_slug = kwargs.get("category_slug")
            tag_slug = kwargs.get("tag_slug")
            context["blog_posts"] = self.get_blog_posts(
                category_slug=category_slug, tag_slug=tag_slug, preview=preview
            )
            context["category_slug"] = category_slug
            context["tag_slug"] = tag_slug
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)


class ButterCMSBlogSearchView(ButterCMSPageView):
    template_name = "content/blog.html"

    @xframe_options_exempt
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            search_query = request.GET.get("q")
            preview = request.GET.get("preview")
            context["blog_posts"] = self.search_blog_posts(search_query)
            context["search_query"] = search_query
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)


class ButterCMSBlogPostView(ButterCMSBlogView):
    template_name = "content/blog-post.html"

    @xframe_options_exempt
    def get(self, request, slug, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # Check if API Token is set properly
        if settings.BUTTERCMS_API_TOKEN:
            preview = request.GET.get("preview")
            blog_post = self.get_blog_post(slug)
            context["blog_post"] = blog_post
            context["categories"] = client.categories.all().get("data")
            context["navigation_menu"] = self.get_navigation_menu()
        else:
            context["no_token"] = True

        return self.render_to_response(context)

    def get_blog_post(self, slug):
        """
        Return a blog post from ButterCMS. Raise 404 if the post is not found
        """
        try:
            butter_post = client.posts.get(slug)
            post_data = butter_post.get("data")
            post_data['published'] = dateparse.parse_datetime(post_data['published'])

            return post_data
        except HTTPError as error:
            if str(error) == "401":
                # log error if token is invalid
                logger.error(
                    """***Your Butter token is set to an invalid value. Please verify your token is correct.***"""
                )
                raise Http404("""***Your Butter token is set to an invalid value. Please verify your token is correct.***""")
            else:
                logger.error(
                    """***Couldn't fetch page.***"""
                )
                raise Http404

django_starter_buttercms/templates/content/partials/blog-posts.html
{% if not no_token %}
<section id="blog" class="blog-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-10">
                <div class="section-title text-center">
                    <h2>Latest Blog Posts</h2>
                    <p>Butter also has a built in blog engine which makes it dead simple to launch a new company blog.</p>
                    <p>
						<a 
							href="{% url 'content:blog' locale_slug=locale %}" 
							class="main-btn btn-hover mt-5">View All Blog Posts
						</a>
						</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            {% for blog_post in blog_posts %}
                {% if forloop.counter == 1 or forloop.counter == 2 %}
                    <div class="col-lg-4 col-md-8 col-sm-10">
                        <div class="single-blog single-post-thumbnail">
                            {% if blog_post.featured_image %}
                            <div class="blog-header">
                                <img width="300" src="{{ blog_post.featured_image }}" alt="{{ blog_post.featured_image_alt }}">
                            </div>
                            {% endif %}
                            <div class="blog-body">
                                <h5 class="package-name"><a href="{% url 'content:blog_post' slug=blog_post.slug %}">{{ blog_post.title }}</a></h5>
                                <p>{{ blog_post.summary }}</p>
                            </div>
                            <div class="blog-footer">
                                <a href="{% url 'content:blog_post' locale_slug=locale slug=blog_post.slug %}" class="main-btn btn-hover">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{% endif %}

django_starter_buttercms/templates/content/partials/blog-search-and-categories.html
 {% if not no_token %}
 <aside class="col-12 col-lg-4">
    <div class="sidebar blog-grid-page">
        <div class="widget search-widget">
            <h5 class="widget-title">Search This Site</h5>
            <form action="{% url 'content:blog_search' locale_slug=locale %}">
                <input type="text" name="q" placeholder="Search Here..." {% if search_query %}value="{{ search_query }}"{% endif %}>
                <button type="submit"><i class="lni lni-search-alt"></i></button>
            </form>
        </div>
    </div>

    <div class="widget categories-widget">
        <h5 class="widget-title">Categories</h5>
        <ul class="categories-list">
            {% for category in categories %}
            <li>
                <a href="{% url 'content:blog_category' locale_slug=locale category_slug=category.slug %}">{{ category.name }}</a>
            </li>
            {% endfor %}
        </div>
    </div>
</aside>
{% endif %}

django_starter_buttercms/templates/content/partials/missing-component.html
<div>
    <h3>Missing a template for {{ component_name }}</h3>
    <p>Expected a template <code>templates/component/{{ component_name }}.html</code> but didn't find it.</p>
    <p>Component details: <code>{{ component }}</code></p>
</div>